name: ci
on:
  push:
    branches:
      - main
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: ./current-repo

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: SolP-Aleios/mock-docs-repo
          path: ./docs-repo

      - name: Copy Directory
        run: cp -R ./current-repo/docs ./docs-repo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          path: ./docs-repo
