name: ci
on:
  push:
    branches:
      - main
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "docs"
          destination_repo: "SolP-Aleios/mock-docs-repo"
          destination_branch: "update-docs"
          user_email: "solp@aleios.com"
          user_name: "SolP-Aleios"
          commit_message: "feat: updated docs"
